### ISSUE TITLE
As a player I want to see who the current active player is in the players list

### ISSUE THREAD

**Issue by nicoszolderits** [SE-II-group2/catan-android#75]

**Comment by jastornig** [comment]
Is das schon Fertig? Gibts da an Branch?

**Comment by nicoszolderits** [comment]
Ist fertig und hab ich auf meinem branch refactor-board-ui-drawing hinzugefügt weil das eh nur UI ist und nur ein paar Zeilen waren. Mach für den Branch jz mal eine PR auf, aber können wir sonst am Dienstag kurz durchgehen einfach. Dem aktiven Spieler wird jetzt immer ein weißer Punkt neben dem Namen angezeigt.
