### ISSUE TITLE
Creating a trading UI-Sketch between two players according to peer review

### ISSUE THREAD

**Issue by yikesboy** [SE-II-group2/catan-android#8]

**Comment by Ghost-Element** [comment]
![trade_sketch_2](https://github.com/SE-II-group2/catan-android/assets/162124658/e95dc177-3099-4bb1-bda8-3fa951dacc06)
![trade_sketch_1](https://github.com/SE-II-group2/catan-android/assets/162124658/d08f24af-30f4-406f-8dab-374e74f967f1)
